function print_specs(hardware, eye, sim)
    fprintf(strcat('Simultion parameters: \nf0=', ...
                num2str(hardware.f0*1000),'mm, \nfe=', ...
                num2str(eye.eyepiece_f*1000),'mm, \neye_diameter=', ...
                num2str(eye.eye_diameter*1000), 'mm, \nworking_range=', ...
                num2str(hardware.working_range), ', \nnum_focus_images=', ...
                num2str(sim.num_focus_images), ', \nsim_resolution=', ...
                num2str(sim.resolution*1e6), 'um, \nN=', ...
                num2str(sim.N), ', \nnum_iter=', ...
                num2str(sim.num_iter), '\n'))
end